#!/usr/bin/env python3

try:
	from sccm import *
except ModuleNotFoundError:
	import sys
	sys.path.append('../') #for debugging ./sccm
	from sccm import *

from tqdm import *

def run():
	p = Parameters()  # load default parameters
	model = PaperModel(p)
	model.run()
	model.save_results()

if __name__ == "__main__":
	run()
