#!/usr/bin/env python3

import argparse

import pandas as pd

parser = argparse.ArgumentParser(description='average over multiple rund')
parser.add_argument('-i', nargs='+', dest='infilenames', help='input pickle df files', required=True)
parser.add_argument('-o', action='store', dest='outdir', help='output directory', default = '')

args = parser.parse_args()

print('input files: ', args.infilenames)
print('output dir: ', args.outdir)


dfs = []
for f in args.infilenames:
    dfs.append(pd.read_pickle(f))

mean = pd.concat(dfs).groupby(level=0).mean()
st = pd.concat(dfs).groupby(level=0).std()
mx = pd.concat(dfs).groupby(level=0).max()
mi = pd.concat(dfs).groupby(level=0).min()


mean.to_pickle(args.outdir+'mean.pkl')
mi.to_pickle(args.outdir+'min.pkl')
mx.to_pickle(args.outdir+'max.pkl')
st.to_pickle(args.outdir+'std.pkl')
