#!/usr/bin/env python3

import argparse

import pandas as pd

parser = argparse.ArgumentParser(description='average over multiple rund')
parser.add_argument('-i', nargs='+', dest='infilenames', help='input pickle df files', required=True)
parser.add_argument('-o', action='store', dest='outfilename', help='output pickle df file', required=True)

#TODO: plt.save instead of showing on screen

args = parser.parse_args()

print('input files: ', args.infilenames)
print('output: ', args.outfilename)


dfs = []
for f in args.infilenames:
    dfs.append(pd.read_pickle(f))

mean = pd.concat(dfs).groupby(level=0).mean()
st = pd.concat(dfs).groupby(level=0).std()
mx = pd.concat(dfs).groupby(level=0).min()
mi = pd.concat(dfs).groupby(level=0).max()


mean.to_pickle(args.outfilename)
mi.to_pickle('min_'+args.outfilename)
mx.to_pickle('max_'+args.outfilename)
st.to_pickle('std_'+args.outfilename)
