function createfigure(Y1,str,str2)
%CREATEFIGURE1(Y1)
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 25-Nov-2012 21:38:28

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YScale','log','YMinorTick','on',...
    'YMinorGrid','on',...
    'YGrid','on',...
    'XScale','log',...
    'XMinorTick','on',...
    'XMinorGrid','on',...
    'XGrid','on');
box(axes1,'on');
hold(axes1,'all');

% Create loglog
loglog(Y1,'MarkerEdgeColor',[1 0 0],'MarkerSize',5,...
    'Marker','o',...
    'LineStyle','none');

% Create labels and legend
xlabel('Cluster size');
ylabel('Count');
legend(str);

%Save figure as bmp and/or post-script (eps) or matlab figure (fig) 
%Fabian: Using BMP gave me an error, .fig works better and is also reopenable in matlab
%saveas(figure1,['Data/',str2,'/ClustSizeDistr.bmp'],'bmp');
saveas(figure1,['Data/',str2,'/ClustSizeDistr.jpg'],'jpg');
saveas(figure1,['Data/',str2,'/ClustSizeDistr.fig'],'fig');

