function createfigure(Y1,str)
%CREATEFIGURE1(Y1)
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 25-Nov-2012 21:38:28

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YScale','log','YMinorTick','on',...
    'YMinorGrid','on',...
    'YGrid','on',...
    'XScale','log',...
    'XMinorTick','on',...
    'XMinorGrid','on',...
    'XGrid','on');
xlim(axes1,[1 300]);
ylim(axes1,[0.0003 1]);
box(axes1,'on');
hold(axes1,'all');

% Create loglog
loglog(Y1/sum(Y1),'MarkerFaceColor',[1 0 0],'MarkerEdgeColor',[0 0 0],...
    'MarkerSize',6,...
    'Marker','o',...
    'LineStyle','none');

% Create labels and legend
xlabel('Cluster size S');
ylabel('Probability P(S)');
legend(str);


%Save figure as bmp and/or post-script (eps) or matlab figure (fig) 
%Fabian: Using BMP gave me an error, .fig works better and is also reopenable in matlab
%saveas(figure1,['Data/',str2,'/ClustSizeDistr.bmp'],'bmp');
%saveas(figure1,['Data/',str2,'/ClustSizeDistr.jpg'],'jpg');
%saveas(figure1,['Data/',str2,'/ClustSizeDistr.fig'],'fig');

