%%This is simply a data-plotter of data generated by main_script.m
k_avg_set = 4;
N = 500;
gamma = 10;
ii = 10;

phi_range = 0.1:0.1:0.9; %Explicitly define this vector outside of the for-loop such that it can be used for plotting.
%op = zeros(length(phi_range));
op = [];

for phi=phi_range
    str2=['N',num2str(N),'k',num2str(k_avg_set),'gamma',num2str(gamma),'Phi',num2str(phi),'Runs',num2str(ii)];
    load(['Data/',str2,'/AllFinVar.mat']);
    op = [op find(s_avg, 1, 'last' )/N]; %Concatenate the value of the size of the biggest cluster for a given phi. The command finds the 1 last non-zero entry of s.
end

plot(phi_range, op, 'x')